pull_request_rules:
  - name: automatic merge if author is coder-do
    conditions:
      - author=coder-do
      - check-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge

  - name: automatic merge if author is renovate
    conditions:
      - author=renovate
      - check-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge