pull_request_rules:
  - name: automatic merge if author is owner
    conditions:
      - author=coder-do
    actions:
      merge:
        method: merge

  - name: automatic merge if author is renovate
    conditions:
      - author=renovat[bot]
    actions:
      merge:
        method: merge
